[PuyoConfig]
SearchLocations = [[2, 4], [3, 4], [4, 4], [5, 4], [2, 3], [3, 3], [4, 3], [5, 3], [3, 2], [4, 2], [5, 2], [2, 1], [3, 1], [4, 1], [5, 1]]
Field = "a61ca5c2a3c2a4"
Mappings = { a = 4, b = 5, c = 6, d = 7, " " = 0 }
