[PuyoConfig]
SearchLocations = [[2, 4], [3, 4], [4, 4], [5, 4], [3, 3], [4, 3], [5, 3], [3, 1], [4, 1], [5, 1], [4, 5], [5, 5]]
Field = "a61eda4e2d3e2da3"
Mappings = { a = 4, b = 5, c = 6, d = 7, " " = 0 }
